version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      # install npm
      - npm install --force

  build:
    commands:
      # run build script
      - npm run-script prod:build

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
# artifacts:
#   files:
#     - .elasticbeanstalk/**/*
#     - build/**/*
#     - public/**/*
#     - src/**/*
#     - package.json
#     - appspec.yml
#     - buildspec.yml
#     - scripts/**/*
